src/Admin/Controllers/ToolsController.cs
using System.Text;
using System.Text.Json;
using Bit.Admin.Enums;
using Bit.Admin.Models;
using Bit.Admin.Utilities;
using Bit.Core.AdminConsole.Entities;
using Bit.Core.Entities;
using Bit.Core.Models.BitStripe;
using Bit.Core.OrganizationFeatures.OrganizationLicenses.Interfaces;
using Bit.Core.Repositories;
using Bit.Core.Services;
using Bit.Core.Settings;
using Bit.Core.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bit.Admin.Controllers;

[Authorize]
[SelfHosted(NotSelfHostedOnly = true)]
public class ToolsController : Controller
{
    private readonly GlobalSettings _globalSettings;
    private readonly IOrganizationRepository _organizationRepository;
    private readonly ICloudGetOrganizationLicenseQuery _cloudGetOrganizationLicenseQuery;
    private readonly IUserService _userService;
    private readonly ITransactionRepository _transactionRepository;
    private readonly IInstallationRepository _installationRepository;
    private readonly IOrganizationUserRepository _organizationUserRepository;
    private readonly IPaymentService _paymentService;
    private readonly ITaxRateRepository _taxRateRepository;
    private readonly IStripeAdapter _stripeAdapter;
    private readonly IWebHostEnvironment _environment;

    public ToolsController(
        GlobalSettings globalSettings,
        IOrganizationRepository organizationRepository,
        ICloudGetOrganizationLicenseQuery cloudGetOrganizationLicenseQuery,
        IUserService userService,
        ITransactionRepository transactionRepository,
        IInstallationRepository installationRepository,
        IOrganizationUserRepository organizationUserRepository,
        ITaxRateRepository taxRateRepository,
        IPaymentService paymentService,
        IStripeAdapter stripeAdapter,
        IWebHostEnvironment environment)
    {
        _globalSettings = globalSettings;
        _organizationRepository = organizationRepository;
        _cloudGetOrganizationLicenseQuery = cloudGetOrganizationLicenseQuery;
        _userService = userService;
        _transactionRepository = transactionRepository;
        _installationRepository = installationRepository;
        _organizationUserRepository = organizationUserRepository;
        _taxRateRepository = taxRateRepository;
        _paymentService = paymentService;
        _stripeAdapter = stripeAdapter;
        _environment = environment;
    }

    [RequirePermission(Permission.Tools_ChargeBrainTreeCustomer)]
    public IActionResult ChargeBraintree()
    {
        return View(new ChargeBraintreeModel());
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [RequirePermission(Permission.Tools_ChargeBrainTreeCustomer)]
    public async Task<IActionResult> ChargeBraintree(ChargeBraintreeModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var btGateway = new Braintree.BraintreeGateway
        {
            Environment = _globalSettings.Braintree.Production ?
                Braintree.Environment.PRODUCTION : Braintree.Environment.SANDBOX,
            MerchantId = _globalSettings.Braintree.MerchantId,
            PublicKey = _globalSettings.Braintree.PublicKey,
            PrivateKey = _globalSettings.Braintree.PrivateKey
        };

        var btObjIdField = model.Id[0] == 'o' ? "organization_id" : "user_id";
        var btObjId = new Guid(model.Id.Substring(1, 32));

        var transactionResult = await btGateway.Transaction.SaleAsync(
            new Braintree.TransactionRequest
            {
                Amount = model.Amount.Value,
                CustomerId = model.Id,
                Options = new Braintree.TransactionOptionsRequest
                {
                    SubmitForSettlement = true,
                    PayPal = new Braintree.TransactionOptionsPayPalRequest
                    {
                        CustomField = $"{btObjIdField}:{btObjId},region:{_globalSettings.BaseServiceUri.CloudRegion}"
                    }
                },
                CustomFields = new Dictionary<string, string>
                {
                    [btObjIdField] = btObjId.ToString(),
                    ["region"] = _globalSettings.BaseServiceUri.CloudRegion
                }
            });

        if (!transactionResult.IsSuccess())
        {
            ModelState.AddModelError(string.Empty, "Charge failed. " +
                "Refer to Braintree admin portal for more information.");
        }
        else
        {
            model.TransactionId = transactionResult.Target.Id;
            model.PayPalTransactionId = transactionResult.Target?.PayPalDetails?.CaptureId;
        }
        return View(model);
    }

    [RequirePermission(Permission.Tools_CreateEditTransaction)]
    public IActionResult CreateTransaction(Guid? organizationId = null, Guid? userId = null)
    {
        return View("CreateUpdateTransaction", new CreateUpdateTransactionModel
        {
            OrganizationId = organizationId,
            UserId = userId
        });
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [RequirePermission(Permission.Tools_CreateEditTransaction)]
    public async Task<IActionResult> CreateTransaction(CreateUpdateTransactionModel model)
    {
        if (!ModelState.IsValid)
        {
            return View("CreateUpdateTransaction", model);
        }

        await _transactionRepository.CreateAsync(model.ToTransaction());
        if (model.UserId.HasValue)
        {
            return RedirectToAction("Edit", "Users", new { id = model.UserId });
        }
        else
        {
            return RedirectToAction("Edit", "Organizations", new { id = model.OrganizationId });
        }
    }

    [RequirePermission(Permission.Tools_CreateEditTransaction)]
    public async Task<IActionResult> EditTransaction(Guid id)
    {
        var transaction = await _transactionRepository.GetByIdAsync(id);
        if (transaction == null)
        {
            return RedirectToAction("Index", "Home");
        }
        return View("CreateUpdateTransaction", new CreateUpdateTransactionModel(transaction));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [RequirePermission(Permission.Tools_CreateEditTransaction)]
    public async Task<IActionResult> EditTransaction(Guid id, CreateUpdateTransactionModel model)
    {
        if (!ModelState.IsValid)
        {
            return View("CreateUpdateTransaction", model);
        }
        await _transactionRepository.ReplaceAsync(model.ToTransaction(id));
        if (model.UserId.HasValue)
        {
            return RedirectToAction("Edit", "Users", new { id = model.UserId });
        }
        else
        {
            return RedirectToAction("Edit", "Organizations", new { id = model.OrganizationId });
        }
    }

    [RequirePermission(Permission.Tools_PromoteAdmin)]
    public IActionResult PromoteAdmin()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [RequirePermission(Permission.Tools_PromoteAdmin)]
    public async Task<IActionResult> PromoteAdmin(PromoteAdminModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var orgUsers = await _organizationUserRepository.GetManyByOrganizationAsync(
            model.OrganizationId.Value, null);
        var user = orgUsers.FirstOrDefault(u => u.UserId == model.UserId.Value);
        if (user == null)
        {
            ModelState.AddModelError(nameof(model.UserId), "User Id not found in this organization.");
        }
        else if (user.Type != Core.Enums.OrganizationUserType.Admin)
        {
            ModelState.AddModelError(nameof(model.UserId), "User is not an admin of this organization.");
        }

        if (!ModelState.IsValid)
        {
            return View(model);
        }

        user.Type = Core.Enums.OrganizationUserType.Owner;
        await _organizationUserRepository.ReplaceAsync(user);
        return RedirectToAction("Edit", "Organizations", new { id = model.OrganizationId.Value });
    }

    [RequirePermission(Permission.Tools_GenerateLicenseFile)]
    public IActionResult GenerateLicense()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [RequirePermission(Permission.Tools_GenerateLicenseFile)]
    public async Task<IActionResult> GenerateLicense(LicenseModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        User user = null;
        Organization organization = null;
        if (model.UserId.HasValue)
        {
            user = await _userService.GetUserByIdAsync(model.UserId.Value);
            if (user == null)
            {
                ModelState.AddModelError(nameof(model.UserId), "User Id not found.");
            }
        }
        else if (model.OrganizationId.HasValue)
        {
            organization = await _organizationRepository.GetByIdAsync(model.OrganizationId.Value);
            if (organization == null)
            {
                ModelState.AddModelError(nameof(model.OrganizationId), "Organization not found.");
            }
            else if (!organization.Enabled)
            {
                ModelState.AddModelError(nameof(model.OrganizationId), "Organization is disabled.");
            }
        }
        if (model.InstallationId.HasValue)
        {
            var installation = await _installationRepository.GetByIdAsync(model.InstallationId.Value);
            if (installation == null)
            {
                ModelState.AddModelError(nameof(model.InstallationId), "Installation not found.");
            }
            else if (!installation.Enabled)
            {
                ModelState.AddModelError(nameof(model.OrganizationId), "Installation is disabled.");
            }
        }

        if (!ModelState.IsValid)
        {
            return View(model);
        }

        if (organization != null)
        {

src/Admin/Views/Tools/ChargeBraintree.cshtml
@model ChargeBraintreeModel
@{
    ViewData["Title"] = "Charge Braintree Customer";
}

<h1>Charge Braintree Customer</h1>

@if(!string.IsNullOrWhiteSpace(Model.TransactionId))
{
    <div class="alert alert-success" role="alert">
        <p>Charged customer "@Model.Id" for @Model.Amount.Value.ToString("C").</p>
        <strong>btTransactionId:</strong> @Model.TransactionId<br />
        <strong>btPayPalTransactionId:</strong> @Model.PayPalTransactionId
    </div>
    <a asp-action="ChargeBraintree" class="btn btn-secondary">Charge Another Customer</a>
}
else
{
    <form method="post">
        <div asp-validation-summary="All" class="alert alert-danger"></div>
        <div class="row">
            <div class="col-sm">
                <div class="form-group">
                    <label asp-for="Id"></label>
                    <input type="text" class="form-control" asp-for="Id" required
                           placeholder="ex. u298ccf9240b64f7f8b5da9e0003ba287cpz">
                </div>
            </div>
            <div class="col-sm">
                <div class="form-group">
                    <label asp-for="Amount"></label>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">$</span>
                        </div>
                        <input type="number" min="0.01" max="10000.00" step="0.01" class="form-control"
                               asp-for="Amount" required placeholder="ex. 10.00">
                    </div>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary mb-2">Charge Customer</button>
    </form>
}

src/Admin/Views/Tools/CreateUpdateTransaction.cshtml
@model CreateUpdateTransactionModel
@{
    var action = Model.Edit ? "Edit" : "Create";
    ViewData["Title"] = $"{action} Transaction";
}

<h1>@action Transaction</h1>

<form method="post">
    <div asp-validation-summary="All" class="alert alert-danger"></div>
    <div class="row">
        <div class="col-md">
            <div class="form-group">
                <label asp-for="UserId"></label>
                <input type="text" class="form-control" asp-for="UserId">
            </div>
        </div>
        <div class="col-md">
            <div class="form-group">
                <label asp-for="OrganizationId"></label>
                <input type="text" class="form-control" asp-for="OrganizationId">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md">
            <div class="form-group">
                <label asp-for="Date"></label>
                <input type="datetime-local" class="form-control" asp-for="Date" required>
            </div>
        </div>
        <div class="col-md">
            <div class="form-group">
                <div class="form-group">
                    <label asp-for="Type"></label>
                    <select class="form-control" asp-for="Type" required
                            asp-items="Html.GetEnumSelectList<Bit.Core.Enums.TransactionType>()"></select>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md">
            <div class="form-group">
                <label asp-for="Amount"></label>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">$</span>
                    </div>
                    <input type="number" min="-1000000.00" max="1000000.00" step="0.01" class="form-control"
                           asp-for="Amount" required placeholder="ex. 10.00">
                </div>
            </div>
        </div>
        <div class="col-md">
            <div class="form-group">
                <label asp-for="RefundedAmount"></label>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">$</span>
                    </div>
                    <input type="number" min="0.01" max="1000000.00" step="0.01" class="form-control"
                           asp-for="RefundedAmount" placeholder="ex. 10.00">
                </div>
            </div>
        </div>
    </div>
    <div class="form-check mb-3">
        <input type="checkbox" class="form-check-input" asp-for="Refunded">
        <label class="form-check-label" asp-for="Refunded"></label>
    </div>
    <div class="form-group">
        <label asp-for="Details"></label>
        <input type="text" class="form-control" asp-for="Details" required>
    </div>
    <div class="row">
        <div class="col-md">
            <div class="form-group">
                <div class="form-group">
                    <label asp-for="Gateway"></label>
                    <select class="form-control" asp-for="Gateway"
                            asp-items="Html.GetEnumSelectList<Bit.Core.Enums.GatewayType>()">
                        <option value="">--</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="col-md">
            <div class="form-group">
                <label asp-for="GatewayId"></label>
                <input type="text" class="form-control" asp-for="GatewayId">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <div class="form-group">
                    <label asp-for="PaymentMethod"></label>
                    <select class="form-control" asp-for="PaymentMethod"
                            asp-items="Html.GetEnumSelectList<Bit.Core.Enums.PaymentMethodType>()">
                        <option value="">--</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary mb-2">@action Transaction</button>
</form>

src/Admin/Views/Tools/GenerateLicense.cshtml
@model LicenseModel
@{
    ViewData["Title"] = "Generate License File";
}

<h1>Generate License File</h1>

<form method="post">
    <div asp-validation-summary="All" class="alert alert-danger"></div>
    <div class="row">
        <div class="col-md">
            <div class="form-group">
                <label asp-for="UserId"></label>
                <input type="text" class="form-control" asp-for="UserId">
            </div>
        </div>
        <div class="col-md">
            <div class="form-group">
                <label asp-for="OrganizationId"></label>
                <input type="text" class="form-control" asp-for="OrganizationId">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md">
            <div class="form-group">
                <label asp-for="InstallationId"></label>
                <input type="text" class="form-control" asp-for="InstallationId">
            </div>
        </div>
        <div class="col-md">
            <div class="form-group">
                <label asp-for="Version"></label>
                <input type="number" class="form-control" asp-for="Version">
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary mb-2">Generate</button>
</form>

src/Admin/Views/Tools/PromoteAdmin.cshtml
@model PromoteAdminModel
@{
    ViewData["Title"] = "Promote Organization Admin";
}

<h1>Promote Organization Admin</h1>

<form method="post">
    <div asp-validation-summary="All" class="alert alert-danger"></div>
    <div class="row">
        <div class="col-md">
            <div class="form-group">
                <label asp-for="UserId"></label>
                <input type="text" class="form-control" asp-for="UserId">
            </div>
        </div>
        <div class="col-md">
            <div class="form-group">
                <label asp-for="OrganizationId"></label>
                <input type="text" class="form-control" asp-for="OrganizationId">
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary mb-2">Promote Admin</button>
</form>

src/Admin/Views/Tools/TaxRate.cshtml
@model TaxRatesModel
@{
    ViewData["Title"] = "Tax Rates";
}

<h1>Manage Tax Rates</h1>

<h2>Bulk Upload Tax Rates</h2>
<section>
    <p>
        Upload a CSV file containing multiple tax rates in bulk in order to update existing rates by country
        and postal code OR to create new rates where a currently active rate is not found already.
    </p>
    <p>CSV Upload Format</p>
    <ul>
        <li><b>Postal Code</b> (required) - The postal code for the tax rate.</li>
        <li><b>Rate</b> (required) - The effective tax rate for this postal code.</li>
        <li><b>State</b> (<i>optional</i>) - The ISO-2 character code for the state. Optional but recommended.</li>
        <li><b>Country</b> (<i>optional</i>) - The ISO-2 character country code, defaults to "US" if not provided.</li>
    </ul>
    <p>Example (white-space is ignored):</p>
    <div class="card mb-2">
        <div class="card-body">
            <pre class="mb-0">87654,8.25,FL,US
22334,8.5,CA
11223,7</pre>
        </div>
    </div>
    <form method="post" enctype="multipart/form-data" asp-action="TaxRateUpload">
        <div class="form-group">
            <input type="file" name="file" />
        </div>
        <div class="form-group">
            <input type="submit" value="Upload" class="btn btn-primary mb-2" />
        </div>
    </form>
</section>

<hr/>
<h2>View &amp; Manage Tax Rates</h2>
<a class="btn btn-primary mb-2" asp-controller="Tools" asp-action="TaxRateAddEdit">Add a Rate</a>
<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th style="width: 190px;">Id</th>
                <th style="width: 80px;">Country</th>
                <th style="width: 80px;">State</th>
                <th style="width: 150px;">Postal Code</th>
                <th style="width: 160px;">Tax Rate</th>
                <th style="width: 80px;"></th>
            </tr>
        </thead>
        <tbody>
            @if(!Model.Items.Any())
            {
                <tr>
                    <td colspan="6">No results to list.</td>
                </tr>
            }
            else
            {
                @foreach(var rate in Model.Items)
                {
                    <tr>
                        <td>
                            @{
                                var taxRateToEdit = new Dictionary<string, string>
                                {
                                    { "id", rate.Id },
                                    { "stripeTaxRateId", rate.Id }
                                };
                            }
                            <a asp-controller="Tools" asp-action="TaxRateAddEdit" asp-all-route-data="taxRateToEdit">@rate.Id</a>
                        </td>
                        <td>
                            @rate.Country
                        </td>
                        <td>
                            @rate.State
                        </td>
                        <td>
                            @rate.PostalCode
                        </td>
                        <td>
                            @rate.Rate%
                        </td>
                        <td>
                            <a class="delete-button" data-id="@rate.Id" asp-controller="Tools" asp-action="TaxRateArchive" asp-route-stripeTaxRateId="@rate.Id">
                                <i class="fa fa-trash fa-lg fa-fw"></i>
                            </a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

<nav>
    <ul class="pagination">
        @if(Model.PreviousPage.HasValue)
        {
            <li class="page-item">
                <a class="page-link" asp-controller="Tools" asp-action="TaxRate" asp-route-page="@Model.PreviousPage.Value" asp-route-count="@Model.Count">Previous</a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Previous</a>
            </li>
        }
        @if(Model.NextPage.HasValue)
        {
            <li class="page-item">
                <a class="page-link" asp-controller="Tools" asp-action="TaxRate" asp-route-page="@Model.NextPage.Value" asp-route-count="@Model.Count">Next</a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Next</a>
            </li>
        }
    </ul>
</nav>