src/Admin/Models/OrganizationViewModel.cs
using Bit.Core.AdminConsole.Entities;
using Bit.Core.AdminConsole.Entities.Provider;
using Bit.Core.Entities;
using Bit.Core.Enums;
using Bit.Core.Models.Data.Organizations.OrganizationUsers;
using Bit.Core.Vault.Entities;

namespace Bit.Admin.Models;

public class OrganizationViewModel
{
    public OrganizationViewModel() { }

    public OrganizationViewModel(Organization org, Provider provider, IEnumerable<OrganizationConnection> connections,
        IEnumerable<OrganizationUserUserDetails> orgUsers, IEnumerable<Cipher> ciphers, IEnumerable<Collection> collections,
        IEnumerable<Group> groups, IEnumerable<Policy> policies, int secretsCount, int projectCount, int serviceAccountsCount,
        int occupiedSmSeatsCount)

    {
        Organization = org;
        Provider = provider;
        Connections = connections ?? Enumerable.Empty<OrganizationConnection>();
        HasPublicPrivateKeys = org.PublicKey != null && org.PrivateKey != null;
        UserInvitedCount = orgUsers.Count(u => u.Status == OrganizationUserStatusType.Invited);
        UserAcceptedCount = orgUsers.Count(u => u.Status == OrganizationUserStatusType.Accepted);
        UserConfirmedCount = orgUsers.Count(u => u.Status == OrganizationUserStatusType.Confirmed);
        OccupiedSeatCount = UserInvitedCount + UserAcceptedCount + UserConfirmedCount;
        CipherCount = ciphers.Count();
        CollectionCount = collections.Count();
        GroupCount = groups?.Count() ?? 0;
        PolicyCount = policies?.Count() ?? 0;
        var organizationUserStatus = org.Status == OrganizationStatusType.Pending
            ? OrganizationUserStatusType.Invited
            : OrganizationUserStatusType.Confirmed;
        Owners = string.Join(", ",
            orgUsers
            .Where(u => u.Type == OrganizationUserType.Owner && u.Status == organizationUserStatus)
            .Select(u => u.Email));
        Admins = string.Join(", ",
            orgUsers
            .Where(u => u.Type == OrganizationUserType.Admin && u.Status == organizationUserStatus)
            .Select(u => u.Email));
        SecretsCount = secretsCount;
        ProjectsCount = projectCount;
        ServiceAccountsCount = serviceAccountsCount;
        OccupiedSmSeatsCount = occupiedSmSeatsCount;
    }

    public Organization Organization { get; set; }
    public Provider Provider { get; set; }
    public IEnumerable<OrganizationConnection> Connections { get; set; }
    public string Owners { get; set; }
    public string Admins { get; set; }
    public int UserInvitedCount { get; set; }
    public int UserConfirmedCount { get; set; }
    public int UserAcceptedCount { get; set; }
    public int OccupiedSeatCount { get; set; }
    public int CipherCount { get; set; }
    public int CollectionCount { get; set; }
    public int GroupCount { get; set; }
    public int PolicyCount { get; set; }
    public bool HasPublicPrivateKeys { get; set; }
    public int SecretsCount { get; set; }
    public int ProjectsCount { get; set; }
    public int ServiceAccountsCount { get; set; }
    public int OccupiedSmSeatsCount { get; set; }
    public bool UseSecretsManager => Organization.UseSecretsManager;
}

src/Admin/Models/ProviderViewModel.cs
using Bit.Core.AdminConsole.Entities.Provider;
using Bit.Core.AdminConsole.Enums.Provider;
using Bit.Core.AdminConsole.Models.Data.Provider;

namespace Bit.Admin.Models;

public class ProviderViewModel
{
    public ProviderViewModel() { }

    public ProviderViewModel(Provider provider, IEnumerable<ProviderUserUserDetails> providerUsers, IEnumerable<ProviderOrganizationOrganizationDetails> organizations)
    {
        Provider = provider;
        UserCount = providerUsers.Count();
        ProviderAdmins = providerUsers.Where(u => u.Type == ProviderUserType.ProviderAdmin);

        ProviderOrganizations = organizations.Where(o => o.ProviderId == provider.Id);
    }

    public int UserCount { get; set; }
    public Provider Provider { get; set; }
    public IEnumerable<ProviderUserUserDetails> ProviderAdmins { get; set; }
    public IEnumerable<ProviderOrganizationOrganizationDetails> ProviderOrganizations { get; set; }
}

src/Admin/Controllers/OrganizationsController.cs
using Bit.Admin.Enums;
using Bit.Admin.Models;
using Bit.Admin.Services;
using Bit.Admin.Utilities;
using Bit.Core.AdminConsole.Entities;
using Bit.Core.AdminConsole.Repositories;
using Bit.Core.Context;
using Bit.Core.Enums;
using Bit.Core.Exceptions;
using Bit.Core.Models.OrganizationConnectionConfigs;
using Bit.Core.OrganizationFeatures.OrganizationSponsorships.FamiliesForEnterprise.Interfaces;
using Bit.Core.Repositories;
using Bit.Core.SecretsManager.Repositories;
using Bit.Core.Services;
using Bit.Core.Settings;
using Bit.Core.Tools.Enums;
using Bit.Core.Tools.Models.Business;
using Bit.Core.Tools.Services;
using Bit.Core.Utilities;
using Bit.Core.Vault.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bit.Admin.Controllers;

[Authorize]
public class OrganizationsController : Controller
{
    private readonly IOrganizationService _organizationService;
    private readonly IOrganizationRepository _organizationRepository;
    private readonly IOrganizationUserRepository _organizationUserRepository;
    private readonly IOrganizationConnectionRepository _organizationConnectionRepository;
    private readonly ISelfHostedSyncSponsorshipsCommand _syncSponsorshipsCommand;
    private readonly ICipherRepository _cipherRepository;
    private readonly ICollectionRepository _collectionRepository;
    private readonly IGroupRepository _groupRepository;
    private readonly IPolicyRepository _policyRepository;
    private readonly IPaymentService _paymentService;
    private readonly ILicensingService _licensingService;
    private readonly IApplicationCacheService _applicationCacheService;
    private readonly GlobalSettings _globalSettings;
    private readonly IReferenceEventService _referenceEventService;
    private readonly IUserService _userService;
    private readonly IProviderRepository _providerRepository;
    private readonly ILogger<OrganizationsController> _logger;
    private readonly IAccessControlService _accessControlService;
    private readonly ICurrentContext _currentContext;
    private readonly ISecretRepository _secretRepository;
    private readonly IProjectRepository _projectRepository;
    private readonly IServiceAccountRepository _serviceAccountRepository;

    public OrganizationsController(
        IOrganizationService organizationService,
        IOrganizationRepository organizationRepository,
        IOrganizationUserRepository organizationUserRepository,
        IOrganizationConnectionRepository organizationConnectionRepository,
        ISelfHostedSyncSponsorshipsCommand syncSponsorshipsCommand,
        ICipherRepository cipherRepository,
        ICollectionRepository collectionRepository,
        IGroupRepository groupRepository,
        IPolicyRepository policyRepository,
        IPaymentService paymentService,
        ILicensingService licensingService,
        IApplicationCacheService applicationCacheService,
        GlobalSettings globalSettings,
        IReferenceEventService referenceEventService,
        IUserService userService,
        IProviderRepository providerRepository,
        ILogger<OrganizationsController> logger,
        IAccessControlService accessControlService,
        ICurrentContext currentContext,
        ISecretRepository secretRepository,
        IProjectRepository projectRepository,
        IServiceAccountRepository serviceAccountRepository)
    {
        _organizationService = organizationService;
        _organizationRepository = organizationRepository;
        _organizationUserRepository = organizationUserRepository;
        _organizationConnectionRepository = organizationConnectionRepository;
        _syncSponsorshipsCommand = syncSponsorshipsCommand;
        _cipherRepository = cipherRepository;
        _collectionRepository = collectionRepository;
        _groupRepository = groupRepository;
        _policyRepository = policyRepository;
        _paymentService = paymentService;
        _licensingService = licensingService;
        _applicationCacheService = applicationCacheService;
        _globalSettings = globalSettings;
        _referenceEventService = referenceEventService;
        _userService = userService;
        _providerRepository = providerRepository;
        _logger = logger;
        _accessControlService = accessControlService;
        _currentContext = currentContext;
        _secretRepository = secretRepository;
        _projectRepository = projectRepository;
        _serviceAccountRepository = serviceAccountRepository;
    }

    [RequirePermission(Permission.Org_List_View)]
    public async Task<IActionResult> Index(string name = null, string userEmail = null, bool? paid = null,
        int page = 1, int count = 25)
    {
        if (page < 1)
        {
            page = 1;
        }

        if (count < 1)
        {
            count = 1;
        }

        var skip = (page - 1) * count;
        var organizations = await _organizationRepository.SearchAsync(name, userEmail, paid, skip, count);
        return View(new OrganizationsModel
        {
            Items = organizations as List<Organization>,
            Name = string.IsNullOrWhiteSpace(name) ? null : name,
            UserEmail = string.IsNullOrWhiteSpace(userEmail) ? null : userEmail,
            Paid = paid,
            Page = page,
            Count = count,
            Action = _globalSettings.SelfHosted ? "View" : "Edit",
            SelfHosted = _globalSettings.SelfHosted
        });
    }

    public async Task<IActionResult> View(Guid id)
    {
        var organization = await _organizationRepository.GetByIdAsync(id);
        if (organization == null)
        {
            return RedirectToAction("Index");
        }

        var provider = await _providerRepository.GetByOrganizationIdAsync(id);
        var ciphers = await _cipherRepository.GetManyByOrganizationIdAsync(id);
        var collections = await _collectionRepository.GetManyByOrganizationIdAsync(id);
        IEnumerable<Group> groups = null;
        if (organization.UseGroups)
        {
            groups = await _groupRepository.GetManyByOrganizationIdAsync(id);
        }
        IEnumerable<Policy> policies = null;
        if (organization.UsePolicies)
        {
            policies = await _policyRepository.GetManyByOrganizationIdAsync(id);
        }
        var users = await _organizationUserRepository.GetManyDetailsByOrganizationAsync(id);
        var billingSyncConnection = _globalSettings.EnableCloudCommunication ? await _organizationConnectionRepository.GetByOrganizationIdTypeAsync(id, OrganizationConnectionType.CloudBillingSync) : null;
        var secrets = organization.UseSecretsManager ? await _secretRepository.GetSecretsCountByOrganizationIdAsync(id) : -1;
        var projects = organization.UseSecretsManager ? await _projectRepository.GetProjectCountByOrganizationIdAsync(id) : -1;
        var serviceAccounts = organization.UseSecretsManager ? await _serviceAccountRepository.GetServiceAccountCountByOrganizationIdAsync(id) : -1;
        var smSeats = organization.UseSecretsManager
            ? await _organizationUserRepository.GetOccupiedSmSeatCountByOrganizationIdAsync(organization.Id)
            : -1;
        return View(new OrganizationViewModel(organization, provider, billingSyncConnection, users, ciphers, collections, groups, policies,
            secrets, projects, serviceAccounts, smSeats));
    }

    [SelfHosted(NotSelfHostedOnly = true)]
    public async Task<IActionResult> Edit(Guid id)
    {
        var organization = await _organizationRepository.GetByIdAsync(id);
        if (organization == null)
        {
            return RedirectToAction("Index");
        }

        var provider = await _providerRepository.GetByOrganizationIdAsync(id);
        var ciphers = await _cipherRepository.GetManyByOrganizationIdAsync(id);
        var collections = await _collectionRepository.GetManyByOrganizationIdAsync(id);
        IEnumerable<Group> groups = null;
        if (organization.UseGroups)
        {
            groups = await _groupRepository.GetManyByOrganizationIdAsync(id);
        }
        IEnumerable<Policy> policies = null;
        if (organization.UsePolicies)
        {
            policies = await _policyRepository.GetManyByOrganizationIdAsync(id);
        }
        var users = await _organizationUserRepository.GetManyDetailsByOrganizationAsync(id);
        var billingInfo = await _paymentService.GetBillingAsync(organization);
        var billingSyncConnection = _globalSettings.EnableCloudCommunication ? await _organizationConnectionRepository.GetByOrganizationIdTypeAsync(id, OrganizationConnectionType.CloudBillingSync) : null;
        var secrets = organization.UseSecretsManager ? await _secretRepository.GetSecretsCountByOrganizationIdAsync(id) : -1;
        var projects = organization.UseSecretsManager ? await _projectRepository.GetProjectCountByOrganizationIdAsync(id) : -1;
        var serviceAccounts = organization.UseSecretsManager ? await _serviceAccountRepository.GetServiceAccountCountByOrganizationIdAsync(id) : -1;
        var smSeats = organization.UseSecretsManager
            ? await _organizationUserRepository.GetOccupiedSmSeatCountByOrganizationIdAsync(organization.Id)
            : -1;
        return View(new OrganizationEditModel(organization, provider, users, ciphers, collections, groups, policies,
            billingInfo, billingSyncConnection, _globalSettings, secrets, projects, serviceAccounts, smSeats));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [SelfHosted(NotSelfHostedOnly = true)]
    public async Task<IActionResult> Edit(Guid id, OrganizationEditModel model)
    {
        var organization = await GetOrganization(id, model);

        if (organization.UseSecretsManager &&
            !organization.SecretsManagerBeta &&
            !StaticStore.GetPlan(organization.PlanType).SupportsSecretsManager)
        {
            throw new BadRequestException("Plan does not support Secrets Manager");

src/Admin/Views/Providers/AddExistingOrganization.cshtml
@using Bit.SharedWeb.Utilities
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model OrganizationUnassignedToProviderSearchViewModel

@{
    ViewData["Title"] = "Add Existing Organization";
    var providerId = ViewContext.RouteData.Values["id"];
}

<h1>Add Existing Organization</h1>
<div class="row mb-2">
    <div class="col">
        <form class="form-inline mb-2" method="get" asp-route-id="@providerId">
            <label class="sr-only" asp-for="OrganizationName"></label>
            <input type="text" class="form-control mb-2 mr-2 flex-fill" placeholder="@Html.DisplayNameFor(m => m.OrganizationName)" asp-for="OrganizationName" name="name">
            <label class="sr-only" asp-for="OrganizationOwnerEmail"></label>
            <input type="email" class="form-control mb-2 mr-2 flex-fill" placeholder="@Html.DisplayNameFor(m => m.OrganizationOwnerEmail)" asp-for="OrganizationOwnerEmail" name="ownerEmail">
            <button type="submit" class="btn btn-primary mb-2" title="Search" formmethod="get"><i class="fa fa-search"></i> Search</button>
        </form>
    </div>
</div>

<form method="post" id="select-form" asp-route-id="@providerId">
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th style="width: 20px;">All</th>
                <th>Name</th>
                <th style="width: 190px;">Plan</th>
            </tr>
            </thead>
            <tbody>
            @if (!Model.Items.Any())
            {
                <tr>
                    <td colspan="5">No results to list.</td>
                </tr>
            }
            else
            {
                @for (var i = 0; i < Model.Items.Count; i++)
                {
                    <tr>
                        <td class="text-center">
                            @Html.HiddenFor(m => Model.Items[i].Id, new { @readonly = "readonly", autocomplete = "off" })
                            @Html.CheckBoxFor(m => Model.Items[i].Selected)
                        </td>
                        <td>@Html.ActionLink(Model.Items[i].Name, "Edit", "Organizations", new { id = Model.Items[i].Id }, new { target = "_blank" })</td>
                        <td>@(Model.Items[i].PlanType.GetDisplayAttribute()?.Name ?? Model.Items[i].PlanType.ToString())</td>
                    </tr>
                }
            }
            </tbody>
        </table>
    </div>
</form>

<div class="row">
    <div class="col">
        <nav>
            <ul class="pagination">
                @if (Model.PreviousPage.HasValue)
                {
                    <li class="page-item">
                        <a class="page-link" asp-action="AddExistingOrganization" asp-route-id="@providerId" asp-route-page="@Model.PreviousPage.Value"
                           asp-route-count="@Model.Count" asp-route-ownerEmail="@Model.OrganizationOwnerEmail"
                           asp-route-name="@Model.OrganizationName">Previous</a>
                    </li>
                }
                else
                {
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Previous</a>
                    </li>
                }
                @if (Model.NextPage.HasValue)
                {
                    <li class="page-item">
                        <a class="page-link" asp-action="AddExistingOrganization" asp-route-id="@providerId" asp-route-page="@Model.NextPage.Value"
                           asp-route-count="@Model.Count" asp-route-ownerEmail="@Model.OrganizationOwnerEmail"
                           asp-route-name="@Model.OrganizationName">Next</a>
                    </li>
                }
                else
                {
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Next</a>
                    </li>
                }
            </ul>
        </nav>
    </div>
    <div class="col-auto">
        <button type="submit" class="btn btn-primary" form="select-form">Add to Reseller</button>
    </div>
</div>

src/Admin/Views/Providers/Admins.cshtml
@using Bit.Admin.Enums;
@using Bit.Core.AdminConsole.Enums.Provider
@inject Bit.Admin.Services.IAccessControlService AccessControlService
@model ProviderViewModel

@{
    var canResendEmailInvite = AccessControlService.UserHasPermission(Permission.Provider_ResendEmailInvite);
}

<h2>Provider Admins</h2>
<div class="row">
    <div class="col-8">
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th style="width: 190px;">Email</th>
                        <th style="width: 40px;">Status</th>
                        <th style="width: 30px;"></th>
                    </tr>
                </thead>
                <tbody>
                    @if(!Model.ProviderAdmins.Any())
                    {
                        <tr>
                            <td colspan="6">No results to list.</td>
                        </tr>
                    }
                    else
                    {
                        @foreach(var admin in Model.ProviderAdmins)
                        {
                            <tr>
                                <td class="align-middle">
                                    @admin.Email
                                </td>
                                <td class="align-middle">
                                    @admin.Status
                                </td>
                                <td>
                                    @if(admin.Status.Equals(ProviderUserStatusType.Confirmed) 
                                        && @Model.Provider.Status.Equals(ProviderStatusType.Pending)
                                        && canResendEmailInvite)
                                    {
                                        @if(@TempData["InviteResentTo"] != null && @TempData["InviteResentTo"].ToString() == @admin.UserId.Value.ToString())
                                        {
                                            <button class="btn btn-outline-success btn-sm disabled" disabled>Invite Resent!</button>
                                        }
                                        else
                                        {
                                            <a class="btn btn-outline-secondary btn-sm" 
                                                data-id="@admin.Id" asp-controller="Providers" 
                                                asp-action="ResendInvite" asp-route-ownerId="@admin.UserId" 
                                                asp-route-providerId="@Model.Provider.Id">
                                                Resend Setup Invite
                                            </a>
                                        }
                                    }
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

src/Admin/Views/Providers/Create.cshtml
@using Bit.SharedWeb.Utilities
@using Bit.Core.AdminConsole.Enums.Provider
@model CreateProviderModel
@{
    ViewData["Title"] = "Create Provider";
}

@section Scripts {
    <script>
        function toggleProviderTypeInfo(value) {
            document.querySelectorAll('[id^="info-"]').forEach(el => { el.classList.add('d-none'); });
            document.getElementById('info-' + value).classList.remove('d-none');
        }
    </script>
}

<h1>Create Provider</h1>

<form method="post">
    <div asp-validation-summary="All" class="alert alert-danger"></div>

    <div class="form-group">
        <label asp-for="Type" class="h2"></label>
        @foreach(ProviderType providerType in Enum.GetValues(typeof(ProviderType)))
        {
            var providerTypeValue = (int)providerType;
            <div class="form-check">
                @Html.RadioButtonFor(m => m.Type, providerType, new { id = $"providerType-{providerTypeValue}", @class = "form-check-input", onclick=$"toggleProviderTypeInfo({providerTypeValue})" })
                @Html.LabelFor(m => m.Type, providerType.GetDisplayAttribute()?.GetName(), new { @class = "form-check-label align-middle", @for = $"providerType-{providerTypeValue}" })
                <br/>
                @Html.LabelFor(m => m.Type, providerType.GetDisplayAttribute()?.GetDescription(), new { @class = "form-check-label small text-muted ml-3 align-top", @for = $"providerType-{providerTypeValue}" })
            </div>
        }
    </div>

    <div id="@($"info-{(int)ProviderType.Msp}")" class="form-group @(Model.Type != ProviderType.Msp ? "d-none" : string.Empty)">
        <h2>MSP Info</h2>
        <div class="form-group">
            <label asp-for="OwnerEmail"></label>
            <input type="text" class="form-control" asp-for="OwnerEmail">
        </div>
    </div>

    <div id="@($"info-{(int)ProviderType.Reseller}")" class="form-group @(Model.Type != ProviderType.Reseller ? "d-none" : string.Empty)">
        <h2>Reseller Info</h2>
        <div class="form-group">
            <label asp-for="Name"></label>
            <input type="text" class="form-control" asp-for="Name">
        </div>
        <div class="form-group">
            <label asp-for="BusinessName"></label>
            <input type="text" class="form-control" asp-for="BusinessName">
        </div>
        <div class="form-group">
            <label asp-for="BillingEmail"></label>
            <input type="text" class="form-control" asp-for="BillingEmail">
        </div>
    </div>

    <button type="submit" class="btn btn-primary mb-2">Create Provider</button>
</form>

src/Admin/Views/Providers/CreateOrganization.cshtml
@model OrganizationEditModel
@{
    ViewData["Title"] = "Create Client Organization";
}

@section Scripts {
    @await Html.PartialAsync("_OrganizationFormScripts")

    <script>
        (() => {
            togglePlanFeatures('@((byte)Model.PlanType)');
        })();
    </script>
}

<h1>New Client Organization</h1>

@await Html.PartialAsync("_OrganizationForm", Model)
<div class="d-flex mt-4">
    <button type="submit" class="btn btn-primary" form="edit-form">Save</button>
    <div class="ml-auto d-flex">
        <form asp-controller="Providers" asp-action="Edit" asp-route-id="@Model.Provider.Id"
              onsubmit="return confirm('Are you sure you want to cancel?')">
            <button class="btn btn-outline-secondary" type="submit">Cancel</button>
        </form>
    </div>
</div>

src/Admin/Views/Providers/Edit.cshtml
@using Bit.Admin.Enums;
@inject Bit.Admin.Services.IAccessControlService AccessControlService

@model ProviderEditModel
@{
    ViewData["Title"] = "Provider: " + Model.Provider.Name;

    var canEdit = AccessControlService.UserHasPermission(Permission.Provider_Edit);
}

<h1>Provider <small>@Model.Provider.Name</small></h1>

<h2>Provider Information</h2>
@await Html.PartialAsync("_ViewInformation", Model)
@await Html.PartialAsync("Admins", Model)
<form method="post" id="edit-form">
    <h2>General</h2>
    <dl class="row">
        <dt class="col-sm-4 col-lg-3">Name</dt>
        <dd class="col-sm-8 col-lg-9">@Model.Provider.Name</dd>
    </dl>
    <h2>Business Information</h2>
    <dl class="row">
        <dt class="col-sm-4 col-lg-3">Business Name</dt>
        <dd class="col-sm-8 col-lg-9">@Model.Provider.BusinessName</dd>
    </dl>
    <h2>Billing</h2>
    <div class="row">
        <div class="col-sm">
            <div class="form-group">
                <label asp-for="BillingEmail"></label>
                <input type="email" class="form-control" asp-for="BillingEmail" readonly='@(!canEdit)'>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <div class="form-group">
                <label asp-for="BillingPhone"></label>
                <input type="tel" class="form-control" asp-for="BillingPhone">
            </div>
        </div>
    </div>
</form>
@await Html.PartialAsync("Organizations", Model)
@if (canEdit)
{
    <div class="d-flex mt-4">
        <button type="submit" class="btn btn-primary" form="edit-form">Save</button>
    </div>
}

src/Admin/Views/Providers/Organizations.cshtml
@using Bit.Core.AdminConsole.Enums.Provider
@model ProviderViewModel

@await Html.PartialAsync("_ProviderScripts")

<h2>Provider Organizations</h2>
<div class="row">
    <div class="col-sm">
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th style="width: 50%;">Name</th>
                        <th style="width: 50%;">Status</th>
                        <th>
                            @if (Model.Provider.Type == ProviderType.Reseller)
                            {
                                <div class="float-right text-nowrap">
                                    <a asp-controller="Providers" asp-action="CreateOrganization" asp-route-providerId="@Model.Provider.Id" class="btn btn-sm btn-primary">New Organization</a>
                                    <a asp-controller="Providers" asp-action="AddExistingOrganization" asp-route-id="@Model.Provider.Id" class="btn btn-sm btn-outline-primary">Add Existing Organization</a>
                                </div>
                            }
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @if (!Model.ProviderOrganizations.Any())
                    {
                        <tr>
                            <td colspan="6">No results to list.</td>
                        </tr>
                    }
                    else
                    {
                        @foreach (var org in Model.ProviderOrganizations)
                        {
                            <tr>
                                <td class="align-middle">
                                    <a asp-controller="Organizations" asp-action="Edit" asp-route-id="@org.OrganizationId">@org.OrganizationName</a>
                                </td>
                                <td>
                                    @org.Status
                                </td>
                                <td>
                                    <div class="float-right">
                                        @if (org.Status == OrganizationStatusType.Pending)
                                        {
                                            <a href="#" class="float-right" onclick="return resendOwnerInvite('@org.OrganizationId');">
                                                <i class="fa fa-envelope-o fa-lg" title="Resend Setup Invite"></i>
                                            </a>
                                        }
                                        else
                                        {
                                            <i class="fa fa-envelope-o fa-lg text-secondary"></i>
                                        }
                                    </div>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

src/Admin/Views/Providers/View.cshtml
@model ProviderViewModel
@{
    ViewData["Title"] = "Provider: " + Model.Provider.Name;
}

<h1>Provider <small>@Model.Provider.Name</small></h1>

<h2>Information</h2>
@await Html.PartialAsync("_ViewInformation", Model)
@await Html.PartialAsync("Admins", Model)
@await Html.PartialAsync("Organizations", Model)

src/Admin/Views/Providers/_ProviderScripts.cshtml
<script>
    function resendOwnerInvite(orgId) {
        if (confirm('Resend invite to organization?')) {
            $.ajax({
                type: "POST",
                url: '@Url.Action("ResendOwnerInvite", "Organizations")' + '?id=' + orgId,
                dataType: 'json',
                contentType: false,
                processData: false,
                success: function (response) {
                    alert('Invitation has been resent!');
                },
                error: function (response) {
                    alert("Error!");
                }
            });
        }
        return false;
    }
</script>

src/Admin/Views/Providers/_ViewInformation.cshtml
@using Bit.SharedWeb.Utilities
@using Bit.Core.AdminConsole.Enums.Provider
@model ProviderViewModel
<dl class="row">
    <dt class="col-sm-4 col-lg-3">Id</dt>
    <dd class="col-sm-8 col-lg-9"><code>@Model.Provider.Id</code></dd>

    <dt class="col-sm-4 col-lg-3">Status</dt>
    <dd class="col-sm-8 col-lg-9">@Model.Provider.Status</dd>
    
    <dt class="col-sm-4 col-lg-3">Users</dt>
    <dd class="col-sm-8 col-lg-9">@(Model.Provider.Type == ProviderType.Reseller ? "N/A" : Model.UserCount)</dd>
    
    <dt class="col-sm-4 col-lg-3">Provider Type</dt>
    <dd class="col-sm-8 col-lg-9">@(Model.Provider.Type.GetDisplayAttribute()?.GetName())</dd>
    
    <dt class="col-sm-4 col-lg-3">Created</dt>
    <dd class="col-sm-8 col-lg-9">@Model.Provider.CreationDate.ToString()</dd>

    <dt class="col-sm-4 col-lg-3">Modified</dt>
    <dd class="col-sm-8 col-lg-9">@Model.Provider.RevisionDate.ToString()</dd>
</dl>